# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57405ce120544f32f04b9a2b64e82c291feb2b2b2007313115e42b3950981db0f00b18ad1923888eb64ef23f6a949c75e1f42329e7dfe0ee5bb4cdc2f50f743a

test:
  secret_key_base: 1d1f11be88819a36badafd4285f6eb8446fc90cc362e5d7bcf8f0042a98bb1c4aff217510963c67950fec8820ead546d4d11b40ec451af97e6378b1f4e078098

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
